name: alphazero

actor_lr: 0.0003
critic_lr: 0.0003
optimizer: adam
lr_schedule: linear
gamma: 0.99
gae_lambda: 0.95
value_coef: 0.5
entropy_coef: 0.01
max_grad_norm: 0.5

num_simulations: 6
max_depth: 4
dirichlet_alpha: 0.3
dirichlet_fraction: 0.25
search_method: muzero
search_method_kwargs: {}

total_buffer_size: 512
total_batch_size: 1024
sample_sequence_length: 1
period: 1
warmup_steps: 25
learner_updates_per_cycle: 1
tree_memory_budget_mb: 124
