defaults:
  - /base_config
  - /system: ppo
  - /envs: uldenv2_base
  - _self_

env:
  seed: 0
  env_kwargs:
    target_groups: 10
    max_items: 10
    max_ems: 40
    max_episode_steps: 30
    generator_type: twophase_physics
    max_mult: 5
    prob_split_one_item: 0.3
    split_num_same_items: 6
    min_dimension: 100
    dataset_path: data/eval_data.csv
    uld_preset: PMC-PLD

arch:
  total_timesteps: 2048
  platform: null
  cuda_visible_devices: null
  num_envs: 8
  num_steps: 32

network:
  _delete_: true
  _target_: jax_rl.networks.ModularPolicyValueModel
  input_adapter:
    _target_: jax_rl.networks.RustpalletInputAdapterV2
    d_model: 16
  shared_torso:
    _target_: jax_rl.networks.BinPackTorso
    hidden_dim: 16
    num_heads: 1
    num_layers: 1
  actor_head:
    _target_: jax_rl.networks.BinPackActorHead
    hidden_dim: 16
    num_rotations: 6
  critic_head:
    _target_: jax_rl.networks.BinPackCriticHead
    hidden_dim: 16

checkpointing:
  checkpoint_dir: checkpoints
  checkpoint_name: null
  transfer_weights_only: false
  save_interval_steps: 0
  max_to_keep: 1
  keep_period: null
  resume_from: null

logging:
  log_every: 1
  tensorboard_logdir: runs_tb
  tensorboard_run_name: ppo_uldenv

evaluations:
  default_eval:
    env: ${env}
    env_kwargs:
      max_items: 10
      target_groups: 10
    eval_every: 1
    num_episodes: 160
    max_steps_per_episode: 30
    greedy: true

  stress_eval:
    env: ${env}
    env_kwargs:
      max_items: 25
      max_ems: 50
      max_episode_steps: 25
      uld_preset: PMC-PLD
      generator_type: twophase_physics
      target_groups: 5
      max_mult: 5
      prob_split_one_item: 0.3
      split_num_same_items: 6
      min_dimension: 100
      min_density: 1e-9
      max_density: 1e-2
      dataset_path: data/eval_data.csv
      reward_type: dense
      action_mode: Oriented
      item_representation: Group
      parallel_strategy: None
    eval_every: 1
    num_episodes: 160
    max_steps_per_episode: 40
    greedy: true
